import{initializeApp}from"https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js";
import{getAuth,setPersistence,browserLocalPersistence,signInWithPopup,GoogleAuthProvider,onAuthStateChanged,signOut}from"https://www.gstatic.com/firebasejs/10.8.0/firebase-auth.js";
import{getFirestore,collection,addDoc,deleteDoc,doc,query,where,onSnapshot,writeBatch}from"https://www.gstatic.com/firebasejs/10.8.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyDnneTFty97_4QmcRFOV58AqDUTmzwqtLo",authDomain:"bunkhelper-7ae5b.firebaseapp.com",projectId:"bunkhelper-7ae5b",storageBucket:"bunkhelper-7ae5b.firebasestorage.app",messagingSenderId:"377239213325",appId:"1:377239213325:web:7fab96687d9f5585318c44",measurementId:"G-7ZSZX0SLEH"};
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app);
let user=null,timetable=[],attendance=[],unsubTT=null,unsubAtt=null,target=Number(localStorage.getItem("bunkhelper-target")||75);
const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"],dayOrder=Object.fromEntries(days.map((d,i)=>[d,i]));
const $=id=>document.getElementById(id);
const esc=s=>String(s??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const today=()=>new Date().toLocaleDateString("en-US",{weekday:"long"});
const isoToday=()=>{const d=new Date();return d.toISOString().slice(0,10)};
const mins=t=>{const[a,b]=String(t||"0:0").split(":").map(Number);return a*60+b};
const sort=a=>[...a].sort((x,y)=>(dayOrder[x.day]??99)-(dayOrder[y.day]??99)||String(x.time).localeCompare(String(y.time)));
function toast(msg,type="info"){const h=$("toast-host"),e=document.createElement("div");e.className="toast toast-"+type;e.innerHTML="<span>"+esc(msg)+"</span><button>×</button>";e.querySelector("button").onclick=()=>e.remove();h.appendChild(e);setTimeout(()=>e.remove(),3500)}
function view(v){document.querySelectorAll("[data-view]").forEach(x=>x.classList.toggle("hidden",x.dataset.view!==v));document.querySelectorAll("[data-nav]").forEach(x=>x.classList.toggle("active",x.dataset.nav===v));$("page-title").textContent={dashboard:"Dashboard",timetable:"Timetable",attendance:"Mark Attendance",history:"History",settings:"Settings"}[v]||"Dashboard";scrollTo({top:0,behavior:"smooth"})}
function dateLabel(){return new Date().toLocaleDateString("en-IN",{weekday:"long",day:"numeric",month:"long",year:"numeric"})}
function findLecture(date,time){const d=new Date(date+"T12:00:00").toLocaleDateString("en-US",{weekday:"long"});return sort(timetable.filter(x=>x.day===d)).sort((a,b)=>Math.abs(mins(a.time)-mins(time))-Math.abs(mins(b.time)-mins(time)))[0]||null}
function recorded(subject,date,time){return attendance.find(x=>x.subject.toLowerCase()===subject.toLowerCase()&&x.date===date&&(time?x.time===time:true))}
function refreshSubjects(){const s=$("att-subject"),old=s.value,subjects=[...new Set(timetable.map(x=>x.subject).filter(Boolean))].sort();s.innerHTML=subjects.length?subjects.map(x=>"<option value='"+esc(x)+"'>"+esc(x)+"</option>").join(""):'<option value="">No timetable classes</option>';s.disabled=!subjects.length;$("subject-hint").textContent=subjects.length?"Pick a lecture. Date + time can automatically select the scheduled subject.":"Add your weekly timetable first.";if(subjects.includes(old))s.value=old}
function suggest(){if(!$("att-date").value||!$("att-time").value)return;const x=findLecture($("att-date").value,$("att-time").value);if(x){$("att-subject").value=x.subject;$("suggestion-box").innerHTML="<strong>Suggested:</strong> "+esc(x.subject)+" · "+esc(x.day)+" "+esc(x.time);$("suggestion-box").classList.remove("hidden")}else $("suggestion-box").classList.add("hidden")}
function renderToday(){const d=today(),items=sort(timetable.filter(x=>x.day===d));$("today-date").textContent=dateLabel();$("today-day-title").textContent=items.length?items.length+" classes scheduled today":"No classes scheduled today";const h=$("today-classes-list");h.innerHTML=items.length?"":"<div class='empty-inline'>No classes scheduled for today.</div>";const now=mins(new Date().toTimeString().slice(0,5));items.forEach(x=>{const a=recorded(x.subject,isoToday(),x.time),state=a?.status==="Present"?"present":a?.status==="Absent"?"absent":mins(x.time)<now?"past":"upcoming";h.insertAdjacentHTML("beforeend","<button class='schedule-chip "+state+"' data-today-subject='"+esc(x.subject)+"' data-today-time='"+esc(x.time)+"'><span class='chip-time'>"+esc(x.time)+"</span><span class='chip-subject'>"+esc(x.subject)+"</span><span class='chip-status'>"+(a?esc(a.status):"Mark")+"</span></button>")})}
function renderMini(){const h=$("mini-timetable"),items=sort(timetable.filter(x=>x.day===today()));h.innerHTML=items.length?items.slice(0,8).map(x=>"<div class='mini-row'><span class='mini-time'>"+esc(x.time)+"</span><span class='mini-subject'>"+esc(x.subject)+"</span><span class='mini-arrow'>→</span></div>").join(""):"<div class='empty-state compact'><div class='empty-icon'>📅</div><h4>No classes today</h4><p>Your saved timetable will appear here.</p><button class='btn' data-go='timetable'>Manage timetable</button></div>"}
function renderTimetable(){const h=$("full-timetable");$("timetable-count").textContent=timetable.length+" classes";h.innerHTML=days.map(d=>{const a=sort(timetable.filter(x=>x.day===d));return"<section class='day-column "+(d===today()?"is-today":"")+"'><div class='day-header'><div><span class='day-name'>"+d+"</span><span class='day-count'>"+a.length+" "+(a.length===1?"class":"classes")+"</span></div>"+(d===today()?"<span class='today-badge'>TODAY</span>":"")+"</div><div class='day-items'>"+(a.length?a.map(x=>"<div class='class-card'><div><span class='class-time'>"+esc(x.time)+"</span><h4>"+esc(x.subject)+"</h4></div><button class='icon-btn' data-delete-tt='"+x.id+"'>×</button></div>").join(""):"<div class='day-empty'>No classes</div>")+"</div></section>"}).join("")}
function renderStats(){const e=attendance.filter(x=>x.status!=="Cancelled"),p=e.filter(x=>x.status==="Present").length,m=e.filter(x=>x.status==="Absent").length,pct=e.length?Math.round(p/e.length*100):0;$("overall-percentage").textContent=pct+"%";$("total-classes").textContent=e.length;$("total-attended").textContent=p;$("total-missed").textContent=m;$("target-inline").textContent=target+"%";$("target-threshold").value=target;const stats={};e.forEach(x=>{stats[x.subject]??={p:0,t:0};stats[x.subject].t++;if(x.status==="Present")stats[x.subject].p++});const h=$("subject-analytics"),rows=Object.entries(stats);h.innerHTML=rows.length?rows.map(([s,v])=>{const q=Math.round(v.p/v.t*100),r=target/100;let advice;if(q>=target){const bunk=Math.max(0,Math.floor((v.p-r*v.t)/r));advice=bunk?"You can miss "+bunk+" more class"+(bunk===1?"":"es")+" and stay at "+target+"%.":"At "+target+"%. Keep attending."}else{const need=Math.ceil((r*v.t-v.p)/(1-r));advice="Attend the next "+need+" class"+(need===1?"":"es")+" to reach "+target+"%."}return"<div class='subject-stat'><div class='subject-stat-top'><div><h4>"+esc(s)+"</h4><span>"+v.p+"/"+v.t+" attended</span></div><strong class='"+(q>=target?"good":"bad")+"'>"+q+"%</strong></div><div class='progress'><span style='width:"+q+"%'></span><i style='left:"+target+"%'></i></div><p>"+esc(advice)+"</p></div>"}).join(""):"<div class='empty-state compact'><div class='empty-icon'>📊</div><h3>No analytics yet</h3><p>Mark attendance and subject-wise stats will appear here.</p></div>";$("target-summary").innerHTML="<div class='target-number'>"+target+"%</div><div><strong>Target</strong><p>Current overall: <b>"+pct+"%</b></p></div>"}
function renderHistory(){const h=$("history-list"),a=[...attendance].sort((x,y)=>(y.date+" "+(y.time||"")).localeCompare(x.date+" "+(x.time||"")));h.innerHTML=a.length?"<div class='history-table-wrap'><table class='history-table'><thead><tr><th>Date</th><th>Subject</th><th>Time</th><th>Status</th><th>Type</th><th></th></tr></thead><tbody>"+a.map(x=>"<tr><td>"+esc(x.date)+"</td><td><strong>"+esc(x.subject)+"</strong></td><td>"+esc(x.time||"—")+"</td><td><span class='status-pill "+String(x.status).toLowerCase()+"'>"+esc(x.status)+"</span></td><td>"+esc(x.type||"Regular")+"</td><td><button class='text-btn danger' data-delete-att='"+x.id+"'>Delete</button></td></tr>").join("")+"</tbody></table></div>":"<div class='empty-state compact'><div class='empty-icon'>✓</div><h3>No attendance logged</h3><p>Your records will appear here.</p></div>"}
async function mark(subject,date,time,status,type="Regular"){if(!user||!subject)return;const duplicate=recorded(subject,date,time);if(duplicate){toast("That lecture is already recorded for this date/time.","warning");return}await addDoc(collection(db,"attendance"),{uid:user.uid,subject,date,time:time||"",status,type,timetableMatch:Boolean(findLecture(date,time||""))});toast(status+": "+subject,status==="Present"?"success":"warning")}
async function deleteRec(col,id){if(!confirm("Delete this record?"))return;try{await deleteDoc(doc(db,col,id))}catch(e){console.error(e);toast("Could not delete record.","error")}}
async function clearTT(){if(!timetable.length)return;if(!confirm("Delete all "+timetable.length+" timetable entries?"))return;const b=writeBatch(db);timetable.forEach(x=>b.delete(doc(db,"timetables",x.id)));await b.commit();toast("Timetable cleared.","success")}
function setup(){document.querySelectorAll("[data-nav]").forEach(b=>b.onclick=()=>view(b.dataset.nav));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>view(b.dataset.go));$("week-view-btn").onclick=()=>view("timetable");$("history-view-btn").onclick=()=>view("history");$("logout-btn").onclick=()=>signOut(auth);
$("target-threshold").onchange=e=>{target=Number(e.target.value);localStorage.setItem("bunkhelper-target",target);renderStats()};
$("att-date").value=isoToday();$("att-time").value=new Date().toTimeString().slice(0,5);["att-date","att-time"].forEach(id=>$(id).addEventListener("input",suggest));
$("attendance-form").onsubmit=async e=>{e.preventDefault();try{await mark($("att-subject").value,$("att-date").value,$("att-time").value,$("att-status").value,$("att-type").value);e.target.reset();$("att-date").value=isoToday();$("att-time").value=new Date().toTimeString().slice(0,5);refreshSubjects();suggest()}catch(err){console.error(err);toast("Could not save attendance. Check Firestore rules.","error")}};
$("quick-present").onclick=()=>mark($("att-subject").value,isoToday(),$("att-time").value,"Present");$("quick-absent").onclick=()=>mark($("att-subject").value,isoToday(),$("att-time").value,"Absent");
$("timetable-form").onsubmit=async e=>{e.preventDefault();try{await addDoc(collection(db,"timetables"),{uid:user.uid,subject:$("subject-input").value.trim(),day:$("day-input").value,time:$("time-input").value});e.target.reset();toast("Class added.","success")}catch(err){console.error(err);toast("Could not add class.","error")}};
$("clear-timetable-btn").onclick=clearTT;$("export-btn").onclick=()=>{const blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),target,timetable,attendance},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="bunkhelper-backup.json";a.click();URL.revokeObjectURL(url);toast("Backup exported.","success")};
$("full-timetable").onclick=e=>{const id=e.target.closest("[data-delete-tt]")?.dataset.deleteTt;if(id)deleteRec("timetables",id)};$("history-list").onclick=e=>{const id=e.target.closest("[data-delete-att]")?.dataset.deleteAtt;if(id)deleteRec("attendance",id)};
$("today-classes-list").onclick=e=>{const b=e.target.closest("[data-today-subject]");if(!b)return;view("attendance");$("att-subject").value=b.dataset.todaySubject;$("att-date").value=isoToday();$("att-time").value=b.dataset.todayTime;$("att-status").value="Present";suggest()};
$("sample-timetable-btn").onclick=async()=>{if(!user)return;const sample=[["Monday","09:00","Constitutional Law I"],["Monday","10:00","Law of Contracts II"],["Tuesday","09:00","Consumer Behaviour"],["Tuesday","10:00","Management Accounting"],["Wednesday","09:00","The Bharatiya Nyaya Sanhita 2023"],["Wednesday","10:00","Macroeconomics"],["Thursday","09:00","Business Ethics & CSR"],["Thursday","10:00","Environmental Management"],["Friday","09:00","Constitutional Law I"],["Friday","10:00","Law of Contracts II"]],b=writeBatch(db);sample.forEach(([day,time,subject])=>{const r=doc(collection(db,"timetables"));b.set(r,{uid:user.uid,day,time,subject})});await b.commit();toast("Sample timetable added. Replace it with your actual schedule.","info")};
$("upload-img-btn").onclick=()=>$("ocr-file-input").click();$("ocr-file-input").onchange=async e=>{const file=e.target.files?.[0];if(!file)return;try{$("ocr-status").textContent="Reading screenshot…";const w=await Tesseract.createWorker("eng"),r=await w.recognize(file);await w.terminate();$("ocr-preview").textContent=r.data.text?.trim()||"No readable text found.";$("ocr-preview-wrap").classList.remove("hidden");$("ocr-status").textContent="OCR complete. Verify the text before adding timetable slots.";toast("Screenshot read successfully.","success")}catch(err){console.error(err);$("ocr-status").textContent="OCR failed.";toast("Could not read screenshot.","error")}}}
function connect(){if(unsubTT)unsubTT();if(unsubAtt)unsubAtt();unsubTT=onSnapshot(query(collection(db,"timetables"),where("uid","==",user.uid)),s=>{timetable=sort(s.docs.map(d=>({id:d.id,...d.data()})));renderToday();renderMini();renderTimetable();refreshSubjects();suggest()},e=>{console.error(e);toast("Timetable failed to load. Check Firestore rules.","error")});unsubAtt=onSnapshot(query(collection(db,"attendance"),where("uid","==",user.uid)),s=>{attendance=s.docs.map(d=>({id:d.id,...d.data()}));renderStats();renderHistory();renderToday()},e=>{console.error(e);toast("Attendance failed to load. Check Firestore rules.","error")})}
$("login-btn").onclick=async()=>{try{await setPersistence(auth,browserLocalPersistence);await signInWithPopup(auth,new GoogleAuthProvider())}catch(e){console.error(e);toast("Login failed: "+e.message,"error")}};
onAuthStateChanged(auth,u=>{if(u){user=u;$("auth-screen").classList.add("hidden");$("app-screen").classList.remove("hidden");$("user-name").textContent=u.displayName||u.email||"Student";$("user-avatar").src=u.photoURL||"";setup();connect();view("dashboard")}else{user=null;$("auth-screen").classList.remove("hidden");$("app-screen").classList.add("hidden");if(unsubTT)unsubTT();if(unsubAtt)unsubAtt()}});
